services:
# Backend services
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data
  backend-dev:
    image: todo-backend-dev
    volumes:
      - ./todo-backend/.:/usr/src/app
    # ports:
    #   - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
# Frontend service
  front-dev:
    image: todo-front-dev
    build:
      context: ./todo-frontend/. # The context will pick this directory as the "build context"
      dockerfile: ./todo-frontend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend/.:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    # ports:
    #   - 5173:5173
    container_name: front-dev # This will name the container hello-front-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - backend-dev
    
    
  todo-reverse-proxy:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - front-dev
      - backend-dev
